### ISSUE TITLE
Peters HUD up no matter what

### ISSUE THREAD

**Issue by egingric** [egingric/2015-Racing-Game#356]
Peters HUD seems to be up no matter what and we are trying to capture footage. Any ideas how to remove that ASAP? @PsteinRCAD

**Comment by PsteinRCAD** [comment]
Is this because right now my VH_vehicle is the default gamemode? A bunch of classmates and I were having this issue as well, but with other people's vehicles. I can temporarily remove my UI creation in my VH_vehicle blueprint so people can work. I will head to campus asap to do this.

**Comment by egingric** [comment]
Um. Yeah. That would do it. I guess I will go and change that back. Did
someone give you permission to check the game mode in?

Regards,
-Eric

**Comment by PsteinRCAD** [comment]
I must have switched it at some point while working on my own level because Max's car wasn't making it through my level very well. (His was the default before that) I guess I must have missed it under my pending list when I reverted unchanged. I am syncing up as I type this, and am about to uhook my UI, unless that isn't needed anymore. I apologize that I seem to be having stupid problems like this lately. I swear I'm not an idiot, haha

**Comment by PsteinRCAD** [comment]
Strange for me, Bianca's car is the default game mode, and her HUD shows up. I still am removing my HUD for now, just in case.

**Comment by egingric** [comment]
Do not remove your hud. Shouldn't be necessary

**Comment by egingric** [comment]
Whatever vehicle you choose in the vehicle select screen will be the hud
that shows up.

Regards,
-Eric
